name: Render RMD to HTML

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup R
      uses: rocker/r-ver@latest

    - name: Install dependencies
      run: |
        install.packages('rmarkdown')
        install.packages('knitr')

    - name: Render RMD file
      run: |
        Rscript -e "rmarkdown::render('bikedata_2024.Rmd')"

    - name: Commit rendered HTML
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add rendered_output.html
        git commit -m 'Rendered RMD file to HTML'
        git push
